name: stillalive
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8080}:3000
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/stillalive}
      - ROOT_URL=${ROOT_URL:-http://localhost}
networks:
  nginx:
    external: true
    name: nginx
