services:
  meteor:
    container_name: stillalive
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 3000
        published: ${PORT:-8080}
    environment:
      MONGO_URL: "${MONGO_URL:-mongodb://mongo:27017/stillalive}"
      ROOT_URL: "${ROOT_URL:-http://localhost}"
networks:
  nginx:
    external: true
    name: nginx
